apiVersion: operator.openshift.io/v1
kind: KubeAPIServer
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2023-11-27T14:06:29Z"
  generation: 4
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: c13a35cc-88dd-4df9-94b6-cb85935e62d3
  resourceVersion: "353898"
  uid: 54c847f2-f968-4abb-bbfe-237e646543c0
spec:
  logLevel: Normal
  managementState: Managed
  observedConfig:
    admission:
      pluginConfig:
        PodSecurity:
          configuration:
            defaults:
              audit: restricted
              audit-version: latest
              enforce: privileged
              enforce-version: latest
              warn: restricted
              warn-version: latest
        network.openshift.io/ExternalIPRanger:
          configuration:
            allowIngressIP: false
            apiVersion: network.openshift.io/v1
            kind: ExternalIPRangerAdmissionConfig
        network.openshift.io/RestrictedEndpointsAdmission:
          configuration:
            apiVersion: network.openshift.io/v1
            kind: RestrictedEndpointsAdmissionConfig
            restrictedCIDRs:
            - 10.128.0.0/14
            - 172.30.0.0/16
    apiServerArguments:
      api-audiences:
      - https://kubernetes.default.svc
      authentication-token-webhook-config-file:
      - /etc/kubernetes/static-pod-resources/secrets/webhook-authenticator/kubeConfig
      authentication-token-webhook-version:
      - v1
      etcd-servers:
      - https://10.19.32.201:2379
      - https://localhost:2379
      feature-gates:
      - AdminNetworkPolicy=false
      - AdmissionWebhookMatchConditions=false
      - AlibabaPlatform=true
      - AutomatedEtcdBackup=false
      - AzureWorkloadIdentity=true
      - BuildCSIVolumes=true
      - CSIDriverSharedResource=false
      - CloudDualStackNodeIPs=true
      - DynamicResourceAllocation=false
      - EventedPLEG=false
      - ExternalCloudProvider=false
      - ExternalCloudProviderAzure=true
      - ExternalCloudProviderExternal=true
      - ExternalCloudProviderGCP=false
      - GCPLabelsTags=false
      - GatewayAPI=false
      - InsightsConfigAPI=false
      - MachineAPIOperatorDisableMachineHealthCheckController=false
      - MachineAPIProviderOpenStack=false
      - MaxUnavailableStatefulSet=false
      - NodeSwap=false
      - OpenShiftPodSecurityAdmission=false
      - PrivateHostedZoneAWS=true
      - RetroactiveDefaultStorageClass=false
      - RouteExternalCertificate=false
      - SigstoreImageVerification=false
      - VSphereStaticIPs=false
      - ValidatingAdmissionPolicy=false
      send-retry-after-while-not-ready-once:
      - "true"
      service-account-issuer:
      - https://kubernetes.default.svc
      service-account-jwks-uri:
      - https://api-int.sno-worker-02.e2e.bos.redhat.com:6443/openid/v1/jwks
      shutdown-delay-duration:
      - 0s
    authConfig:
      oauthMetadataFile: /etc/kubernetes/static-pod-resources/configmaps/oauth-metadata/oauthMetadata
    corsAllowedOrigins:
    - //127\.0\.0\.1(:|$)
    - //localhost(:|$)
    gracefulTerminationDuration: "15"
    servicesSubnet: 172.30.0.0/16
    servingInfo:
      bindAddress: 0.0.0.0:6443
      bindNetwork: tcp4
      cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      minTLSVersion: VersionTLS12
      namedCertificates:
      - certFile: /etc/kubernetes/static-pod-certs/secrets/localhost-serving-cert-certkey/tls.crt
        keyFile: /etc/kubernetes/static-pod-certs/secrets/localhost-serving-cert-certkey/tls.key
      - certFile: /etc/kubernetes/static-pod-certs/secrets/service-network-serving-certkey/tls.crt
        keyFile: /etc/kubernetes/static-pod-certs/secrets/service-network-serving-certkey/tls.key
      - certFile: /etc/kubernetes/static-pod-certs/secrets/external-loadbalancer-serving-certkey/tls.crt
        keyFile: /etc/kubernetes/static-pod-certs/secrets/external-loadbalancer-serving-certkey/tls.key
      - certFile: /etc/kubernetes/static-pod-certs/secrets/internal-loadbalancer-serving-certkey/tls.crt
        keyFile: /etc/kubernetes/static-pod-certs/secrets/internal-loadbalancer-serving-certkey/tls.key
      - certFile: /etc/kubernetes/static-pod-resources/secrets/localhost-recovery-serving-certkey/tls.crt
        keyFile: /etc/kubernetes/static-pod-resources/secrets/localhost-recovery-serving-certkey/tls.key
  operatorLogLevel: Normal
  unsupportedConfigOverrides: null
status:
  conditions:
  - lastTransitionTime: "2023-11-27T14:20:04Z"
    status: "False"
    type: StaticPodFallbackRevisionDegraded
  - lastTransitionTime: "2023-11-27T14:20:04Z"
    reason: AsExpected
    status: "False"
    type: GuardControllerDegraded
  - lastTransitionTime: "2023-11-27T14:20:05Z"
    reason: NoUnsupportedConfigOverrides
    status: "True"
    type: UnsupportedConfigOverridesUpgradeable
  - lastTransitionTime: "2023-11-27T14:20:07Z"
    reason: AllowedFeatureGates_
    status: "True"
    type: FeatureGatesUpgradeable
  - lastTransitionTime: "2023-11-27T14:20:10Z"
    status: "False"
    type: Encrypted
  - lastTransitionTime: "2023-11-27T14:23:28Z"
    status: "False"
    type: CertRotation_ExternalLoadBalancerServing_Degraded
  - lastTransitionTime: "2023-11-27T14:20:17Z"
    status: "False"
    type: CertRotation_LocalhostServing_Degraded
  - lastTransitionTime: "2023-11-27T14:20:22Z"
    status: "False"
    type: CertRotation_AggregatorProxyClientCert_Degraded
  - lastTransitionTime: "2023-11-27T14:20:28Z"
    status: "False"
    type: EncryptionPruneControllerDegraded
  - lastTransitionTime: "2023-11-27T14:20:34Z"
    status: "False"
    type: CertRotation_KubeControllerManagerClient_Degraded
  - lastTransitionTime: "2023-11-27T14:23:37Z"
    reason: AsExpected
    status: "False"
    type: NodeKubeconfigControllerDegraded
  - lastTransitionTime: "2023-11-27T14:20:46Z"
    reason: AsExpected
    status: "False"
    type: KubeAPIServerStaticResourcesDegraded
  - lastTransitionTime: "2023-11-27T14:20:52Z"
    status: "False"
    type: CertRotation_KubeSchedulerClient_Degraded
  - lastTransitionTime: "2023-11-27T14:20:57Z"
    status: "False"
    type: CertRotation_KubeAPIServerToKubeletClientCert_Degraded
  - lastTransitionTime: "2023-11-27T14:21:02Z"
    status: "False"
    type: CertRotation_InternalLoadBalancerServing_Degraded
  - lastTransitionTime: "2023-11-27T14:21:07Z"
    reason: AsExpected
    status: "False"
    type: MissingStaticPodControllerDegraded
  - lastTransitionTime: "2023-11-27T14:21:12Z"
    status: "False"
    type: CertRotation_ControlPlaneNodeAdminClient_Degraded
  - lastTransitionTime: "2023-11-27T14:21:16Z"
    reason: AsExpected
    status: "False"
    type: BackingResourceControllerDegraded
  - lastTransitionTime: "2023-11-27T14:21:21Z"
    status: "False"
    type: CertRotation_ServiceNetworkServing_Degraded
  - lastTransitionTime: "2023-11-27T14:23:25Z"
    status: "False"
    type: StaticPodsDegraded
  - lastTransitionTime: "2023-11-27T14:21:29Z"
    reason: ProfileEmpty
    status: "False"
    type: WorkerLatencyProfileProgressing
  - lastTransitionTime: "2023-11-27T14:21:29Z"
    message: latency profile not set on cluster
    reason: ProfileEmpty
    status: "True"
    type: WorkerLatencyProfileComplete
  - lastTransitionTime: "2023-11-27T14:21:35Z"
    reason: DefaultCertRotationBase
    status: "True"
    type: CertRotationTimeUpgradeable
  - lastTransitionTime: "2023-11-27T14:21:35Z"
    status: "False"
    type: StartupMonitorPodDegraded
  - lastTransitionTime: "2023-11-27T14:21:35Z"
    status: "False"
    type: StartupMonitorPodContainerExcessiveRestartsDegraded
  - lastTransitionTime: "2023-11-28T14:55:44Z"
    status: "False"
    type: InstallerControllerDegraded
  - lastTransitionTime: "2023-11-28T14:59:56Z"
    message: 1 nodes are active; 1 nodes are at revision 12
    status: "True"
    type: StaticPodsAvailable
  - lastTransitionTime: "2023-11-28T19:12:33Z"
    message: 1 nodes are at revision 12
    reason: AllNodesAtLatestRevision
    status: "False"
    type: NodeInstallerProgressing
  - lastTransitionTime: "2023-11-28T14:59:56Z"
    status: "False"
    type: NodeInstallerDegraded
  - lastTransitionTime: "2023-11-28T14:55:49Z"
    status: "False"
    type: MutatingAdmissionWebhookConfigurationError
  - lastTransitionTime: "2023-11-28T19:11:59Z"
    status: "False"
    type: ValidatingAdmissionWebhookConfigurationError
  - lastTransitionTime: "2023-11-27T14:21:35Z"
    status: "False"
    type: CRDConversionWebhookConfigurationError
  - lastTransitionTime: "2023-11-27T14:21:35Z"
    status: "False"
    type: VirtualResourceAdmissionError
  - lastTransitionTime: "2023-11-27T14:21:36Z"
    message: Kubelet and API server minor versions are synced.
    reason: KubeletMinorVersionsSynced
    status: "True"
    type: KubeletMinorVersionUpgradeable
  - lastTransitionTime: "2023-11-27T14:21:36Z"
    message: All master nodes are ready
    reason: MasterNodesReady
    status: "False"
    type: NodeControllerDegraded
  - lastTransitionTime: "2023-11-27T14:21:36Z"
    status: "False"
    type: EncryptionKeyControllerDegraded
  - lastTransitionTime: "2023-11-27T14:21:36Z"
    status: "False"
    type: EncryptionMigrationControllerDegraded
  - lastTransitionTime: "2023-11-27T14:21:36Z"
    status: "False"
    type: EncryptionMigrationControllerProgressing
  - lastTransitionTime: "2023-11-27T14:21:37Z"
    status: "False"
    type: EncryptionStateControllerDegraded
  - lastTransitionTime: "2023-11-27T14:21:37Z"
    status: "False"
    type: CertRotation_NodeSystemAdminClient_Degraded
  - lastTransitionTime: "2023-11-27T14:21:38Z"
    reason: AsExpected
    status: "False"
    type: WorkerLatencyProfileDegraded
  - lastTransitionTime: "2023-11-28T19:10:45Z"
    status: "False"
    type: RevisionControllerDegraded
  - lastTransitionTime: "2023-11-27T14:23:29Z"
    status: "False"
    type: CertRotation_CheckEndpointsClient_Degraded
  - lastTransitionTime: "2023-11-27T14:23:31Z"
    status: "False"
    type: CertRotation_LocalhostRecoveryServing_Degraded
  - lastTransitionTime: "2023-11-27T14:23:32Z"
    status: "False"
    type: InstallerPodPendingDegraded
  - lastTransitionTime: "2023-11-27T14:23:32Z"
    status: "False"
    type: InstallerPodContainerWaitingDegraded
  - lastTransitionTime: "2023-11-27T14:23:32Z"
    status: "False"
    type: InstallerPodNetworkingDegraded
  - lastTransitionTime: "2023-11-27T14:28:42Z"
    status: "False"
    type: ResourceSyncControllerDegraded
  - lastTransitionTime: "2023-11-27T14:23:34Z"
    status: "False"
    type: AuditPolicyDegraded
  - lastTransitionTime: "2023-11-27T14:23:36Z"
    status: "False"
    type: ConfigObservationDegraded
  - lastTransitionTime: "2023-11-28T19:12:05Z"
    status: "False"
    type: TargetConfigControllerDegraded
  latestAvailableRevision: 12
  latestAvailableRevisionReason: ""
  nodeStatuses:
  - currentRevision: 12
    lastFailedCount: 1
    lastFailedReason: InstallerFailed
    lastFailedRevision: 10
    lastFailedRevisionErrors:
    - |
      installer: ing-cert-000",
        (string) (len=21) "user-serving-cert-001",
        (string) (len=21) "user-serving-cert-002",
        (string) (len=21) "user-serving-cert-003",
        (string) (len=21) "user-serving-cert-004",
        (string) (len=21) "user-serving-cert-005",
        (string) (len=21) "user-serving-cert-006",
        (string) (len=21) "user-serving-cert-007",
        (string) (len=21) "user-serving-cert-008",
        (string) (len=21) "user-serving-cert-009"
       },
       CertConfigMapNamePrefixes: ([]string) (len=4 cap=4) {
        (string) (len=20) "aggregator-client-ca",
        (string) (len=9) "client-ca",
        (string) (len=29) "control-plane-node-kubeconfig",
        (string) (len=26) "check-endpoints-kubeconfig"
       },
       OptionalCertConfigMapNamePrefixes: ([]string) (len=1 cap=1) {
        (string) (len=17) "trusted-ca-bundle"
       },
       CertDir: (string) (len=57) "/etc/kubernetes/static-pod-resources/kube-apiserver-certs",
       ResourceDir: (string) (len=36) "/etc/kubernetes/static-pod-resources",
       PodManifestDir: (string) (len=25) "/etc/kubernetes/manifests",
       Timeout: (time.Duration) 2m0s,
       StaticPodManifestsLockFile: (string) "",
       PodMutationFns: ([]installerpod.PodMutationFunc) <nil>,
       KubeletVersion: (string) ""
      })
      I1128 14:56:13.054955       1 cmd.go:410] Getting controller reference for node snonode.sno-worker-02.e2e.bos.redhat.com
      I1128 14:56:13.147742       1 cmd.go:423] Waiting for installer revisions to settle for node snonode.sno-worker-02.e2e.bos.redhat.com
      I1128 14:56:13.161303       1 cmd.go:503] Pod container: installer state for node snonode.sno-worker-02.e2e.bos.redhat.com is not terminated, waiting
      I1128 14:56:23.165662       1 cmd.go:515] Waiting additional period after revisions have settled for node snonode.sno-worker-02.e2e.bos.redhat.com
      I1128 14:56:53.166465       1 cmd.go:521] Getting installer pods for node snonode.sno-worker-02.e2e.bos.redhat.com
      F1128 14:57:07.170326       1 cmd.go:106] Get "https://172.30.0.1:443/api/v1/namespaces/openshift-kube-apiserver/pods?labelSelector=app%3Dinstaller": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    lastFailedTime: "2023-11-28T14:58:08Z"
    nodeName: snonode.sno-worker-02.e2e.bos.redhat.com
  readyReplicas: 0
  serviceAccountIssuers:
  - name: https://kubernetes.default.svc
